/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import edu.princeton.cs.algs4.Draw;

public class App {
    // Atributos
    private Draw draw;

    // Construtor
    public App() {
        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(1000, 600);
        this.draw.setXscale(0,1000);
        this.draw.setYscale(0,600);
    }

    // Main
    public static void main(String[] args){
        App app = new App();

        Grade grade = new Grade(100,100);
        grade.desenhar(app.draw);


        app.draw.show();
    }
}