/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import java.awt.Color;

import edu.princeton.cs.algs4.Draw;

public class App {
    // Atributos
    private Draw draw;

    // Construtor
    public App() {
        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(1000, 600);
        this.draw.setXscale(0,1000);
        this.draw.setYscale(0,600);
    }

    // Main
    public static void main(String[] args){
        App app = new App();

        Grade grade = new Grade(50,100);
        Grade gradeVazio = new Grade(550,100);

        //Definição de navio posicionado seguindo o exemplo do enunciado
        //Coordenada A0
        Navio navioA0 = new Navio(grade, 0, 0, 4, false);
        //Coordenada B5
        Navio navioB5 = new Navio(grade, 5, 1, 3, true);
        //Coordenada C3
        Navio navioC3 = new Navio(grade, 3, 2, 5, true);
        //Coordenada F7
        Navio navioF7 = new Navio(grade, 7, 5, 3, true);
        //Coordenada I1
        Navio navioI1 = new Navio(grade, 1, 8, 2, false);

        //Desenhando os navios
        navioA0.desenhar(app.draw);
        navioB5.desenhar(app.draw);
        navioC3.desenhar(app.draw);
        navioF7.desenhar(app.draw);
        navioI1.desenhar(app.draw);

        //Desenhando a grade
        grade.desenhar(app.draw);
        gradeVazio.desenhar(app.draw);

        //Mostrndo na interface gráfica
        app.draw.show();
    }
}